### ISSUE TITLE
Add disclaimer to bottom of index and project pages

### ISSUE THREAD

**Issue by Lathrisk** [INDIGO-Initiative/golab-website#13]

**Comment by ghost** [comment]
Also - "Ideally this would be a “snippet” so I can enter / edit the text in one place for all pages. "

For adding to index page, can basically copy and paste what I did to put an editable field at top of page.

Not sure about at bottom of project pages - if we do the same there we'll get one PER project, not one for ALL projects. Maybe just fastest to ask for content and put it in template by hand before launch.

**Comment by Lathrisk** [comment]
PR open for this.
